//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBkg.TgClientBot.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotLocalization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotLocalization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("VBkg.TgClientBot.Resources.BotLocalization", typeof(BotLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string EnterAuthCode {
            get {
                return ResourceManager.GetString("EnterAuthCode", resourceCulture);
            }
        }
        
        public static string RemoveBackground_InternalError {
            get {
                return ResourceManager.GetString("RemoveBackground_InternalError", resourceCulture);
            }
        }
        
        public static string RemoveBackground_BackgroundNotFound {
            get {
                return ResourceManager.GetString("RemoveBackground_BackgroundNotFound", resourceCulture);
            }
        }
        
        public static string RemoveBackground_FileTooLarge {
            get {
                return ResourceManager.GetString("RemoveBackground_FileTooLarge", resourceCulture);
            }
        }
        
        public static string RemoveBackground_ImageResolutionTooHigh {
            get {
                return ResourceManager.GetString("RemoveBackground_ImageResolutionTooHigh", resourceCulture);
            }
        }
        
        public static string RemoveBackground_ImageTypeIsNotSupported {
            get {
                return ResourceManager.GetString("RemoveBackground_ImageTypeIsNotSupported", resourceCulture);
            }
        }
        
        public static string RemoveBackground_InsufficientBalance {
            get {
                return ResourceManager.GetString("RemoveBackground_InsufficientBalance", resourceCulture);
            }
        }
        
        public static string RemoveBackground_NotRegisteredInTelegramClientBot {
            get {
                return ResourceManager.GetString("RemoveBackground_NotRegisteredInTelegramClientBot", resourceCulture);
            }
        }
        
        public static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }
    }
}
